terraform_apply:
    name: 'terraform apply'
    needs: [tf_validate]
    runs-on: ubuntu-latest
    environment: dev
    
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: terraform Apply
      if: github.ref == 'refs/heads/development' && github.event_name == 'push'
      run: |
        cd ${{ github.workspace }}/stacks/solo_network
        terraform apply envolve.json -auto-approve
      working-directory: ${{ env.ROOT_PATH }}