name: create ssh publick AKS

runs:
  using: "composite"
  steps:
    run: |
      mkdir -p ~/.ssh/aks-$environmentName-sshkeys-terraform/
      ssh-keygen -f ~/.ssh/aks-$environmentName-sshkeys-terraform/aks$environmentNamesshkey -N ''
      cp ~/.ssh/aks-$environmentName-sshkeys-terraform/*  ${{ github.workspace }}/stacks/solo_network