name: 'Terraform'
on:
  push:
    branches: [ "feature/*" ]
  pull_request:
  workflow_dispatch:
    inputs:
      TFAction:
        description: "Terraform Action- Apply or Destroy"     
        required: true
        default: "apply"


permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    environment: dev

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      TerraformBackendStorageAccount: ${{ secrets.TF_BACKEND_STORAGE_ACCOUNT }}
      TerraformBackendResourceGroup: ${{ secrets.TF_BACKEND_RESOURCE_GROUP }}
      TerraformBackendStorageContainer: ${{ secrets.TF_BACKEND_CONTAINER }}         
      
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      # with:
      #   terraform_wrapper: false
    
    - name: Terraform Init
      run: |
        cd ${{ github.workspace }}/stacks/solo_network
        terraform init -backend-config=storage_account_name=$TerraformBackendStorageAccount -backend-config=container_name=$TerraformBackendStorageContainer -backend-config=key=dev.tfstate -backend-config=resource_group_name=$TerraformBackendResourceGroup -backend-config=subscription_id="$ARM_SUBSCRIPTION_ID" -backend-config=tenant_id="$ARM_TENANT_ID" -backend-config=client_id="$ARM_CLIENT_ID" -backend-config=client_secret="$ARM_CLIENT_SECRET"
 
    - name: Terraform Plan
      run: |
        cd ${{ github.workspace }}/stacks/solo_network
        terraform plan -var-file=../env/infra-base/infra-base.tfvars -out=envolve.tfplan
        
    - name: Terraform fmt
      run: |
        cd ${{ github.workspace }}/stacks/solo_network
        terraform show -no-color -json envolve.tfplan > envolve.json

    - name: Setup Infracost
      run: |
        sudo apt-get update -qq && sudo apt-get -qq install bc curl git
        curl -sL https://github.com/infracost/infracost/releases/latest/download/infracost-linux-amd64.tar.gz | tar xz -C /tmp
        sudo mv /tmp/infracost-linux-amd64 /usr/bin/infracost
        curl -sL -o infracost_diff.sh https://raw.githubusercontent.com/infracost/infracost/master/scripts/ci/diff.sh
        chmod +x infracost_diff.sh
        #./infracost_diff.sh
         infracost breakdown --no-color --path ${{ github.workspace }}/stacks/solo_network/envolve.json

      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken) # Do not change this, it's used to post comments
        INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        path: ${{ github.workspace }}/stacks/solo_network/envolve.json